---
title: "02_plotting"
author: "Katelyn Nguyen"
date: "2025-07-24"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
```

## Tandem Repeats
```{r echo=FALSE}
# Tandem Repeats
data <- data.frame(
  Species = rep(c("C. auris", "C. albicans", "C. glabrata", "K. lactis", "S. cerevisiae"), each = 2),
  Group = rep(c("Putative Adhesins", "Whole Proteome"), times = 5),
  Mean_TR = c(0.273, 0.013, 0.295, 0.018, 0.364, 0.016, 0.312, 0.012, 0.352, 0.013),
  SD = c(0.254, NA, 0.198, NA, 0.229, NA, 0.214, NA, 0.228, NA)
)

# Plot
ggplot(data, aes(x = Species, y = Mean_TR, fill = Group)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = Mean_TR - SD, ymax = Mean_TR + SD),
                position = position_dodge(width = 0.9),
                width = 0.2, na.rm = TRUE) +
  labs(title = "Tandem Repeat % in Putative Adhesins vs. Whole Proteome",
       y = "Mean TR%", x = "Species") +
  scale_fill_manual(values = c("gray70", "steelblue")) +
  theme_minimal(base_size = 20) +
  theme(plot.title = element_text(family = "Helvetica", face = "bold", hjust = 0.5))

```

## Serine/Threonine Frequency
```{r}
st_data <- data.frame(
  Species = rep(c("C. auris", "C. albicans", "C. glabrata", "K. lactis", "S. cerevisiae"), each = 2),
  Group = rep(c("Putative Adhesins", "Whole Proteome"), times = 5),
  Mean_TR = c(0.31614285714286, 0.1420968992, 0.34734146341463, 0.14789942, 0.2992, 0.1392112975, 0.35589285714286, 0.1430392235, 0.40281481481481, 0.1441122836),
  SD = c(0.073061966989728, NA, 0.052903321743695, NA, 0.055544416661103, NA, 0.061842737930123, NA, 0.060022858014468, NA)
)

# Plot
ggplot(st_data, aes(x = Species, y = Mean_TR, fill = Group)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = Mean_TR - SD, ymax = Mean_TR + SD),
                position = position_dodge(width = 0.9),
                width = 0.2, na.rm = TRUE) +
  labs(title = "Tandem Repeat % in Putative Adhesins vs. Whole Proteome",
       y = "Mean S/T Frequency", x = "Species") +
  scale_fill_manual(values = c("gray70", "steelblue")) +
  theme_minimal(base_size = 20) +
  theme(plot.title = element_text(family = "Helvetica", face = "bold", hjust = 0.5))

```

## Beta-Aggregation
```{r}
beta_data <- data.frame(
  Species = rep(c("C. auris", "C. albicans", "C. glabrata", "K. lactis", "S. cerevisiae"), each = 2),
  Group = rep(c("Putative Adhesins", "Whole Proteome"), times = 5),
  Mean_TR = c(4465.715, 2958.407695, 4052.7663414634, 2958.734827, 6568.4882222222, 2826.347839, 2812.9710714286, 2839.59059, 3467.9077777778, 2800.254356),
  SD = c(6605.0358787597, NA, 1931.3576448475, NA, 5615.8530737362, NA, 1366.3415130516, NA, 2889.7353592127, NA)
)

# Plot
ggplot(beta_data, aes(x = Species, y = Mean_TR, fill = Group)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  geom_errorbar(aes(ymin = Mean_TR - SD, ymax = Mean_TR + SD),
                position = position_dodge(width = 0.9),
                width = 0.2, na.rm = TRUE) +
  labs(title = "Tandem Repeat % in Putative Adhesins vs. Whole Proteome",
       y = "Mean Beta-Aggregation per Residue", x = "Species") +
  scale_fill_manual(values = c("gray70", "steelblue")) +
  theme_minimal(base_size = 20) +
  theme(plot.title = element_text(family = "Helvetica", face = "bold", hjust = 0.5))

```
